name: ade-dnd
channels:
  - conda-forge
  - pytorch
defaults:
  - python=3.10

dependencies:
  - python=3.10
  - pip
  - numpy
  - pillow
  - pydantic
  - pyyaml
  - matplotlib
  - tqdm
  - pytorch
  - ipykernel
  - jupyterlab
  - pip:
      - pymupdf
      - transformers>=4.36
      - accelerate
      - sentencepiece
      - paddleocr>=2.7
      - paddlepaddle
      - qwen-vl-utils
      - smolagents
      - opencv-python